### ISSUE TITLE
Order Hardware Components

### ISSUE THREAD

**Issue by rgarofano** [rgarofano/Water-Buddy#1]
The following components need to be ordered:

- (3) RFID tags
- Compatible RFID reader
- Weight sensor
- LCD Display

**Comment by Rajnesh28** [comment]
I'll create a list of hardware items on 9/30/2022 to look over for purchasing.

**Comment by Rajnesh28** [comment]
Here's what I was able to quickly come up with. 

From my understanding the RFID tags are going to be with the water bottles, so they can be any generic tag that we can read, so here's a link to a cheap usable one from Amazon which also comes with an RFID reader that communicates with SPI. 

https://www.amazon.ca/SunFounder-Mifare-Reader-Arduino-Raspberry/dp/B07KGBJ9VG

The following diagram shows which GPIO pins on the BBG can be used for SPI.

![image](https://user-images.githubusercontent.com/75357193/193391771-6d5813fc-a42e-4816-a163-341c403be7b6.png)

Here's a weight sensor that speaks over I2C.

https://abra-electronics.com/sensors/sensors-flex-force-en/sens-50-weight-sensor-to-microcontroller-interface-board.html

Finally, an LCD display which normally would use QSPI but has an I2C converter with it, and our board has multiple GPIO pins dedicated for communicating with various instruments over I2C (see photo below) so we can hopefully use this.

https://www.amazon.ca/KEYESTUDIO-Display-Backlight-Arduino-Raspberry/dp/B0177XQE7K/ref=sr_1_6?crid=XBQ79VCLL5O&keywords=lcd+display&qid=1664597865&qu=eyJxc2MiOiI0Ljc5IiwicXNhIjoiNC4zMSIsInFzcCI6IjMuMzcifQ%3D%3D&sprefix=lcd+displa%2Caps%2C171&sr=8-6

![image](https://user-images.githubusercontent.com/75357193/193392186-5b67d456-fff5-4213-bbcc-d02433b36b59.png)

I'll come back to this in a couple of days and confirm the feasibility of these items that I've suggested after completing some other homework.

**Comment by rgarofano** [comment]
5KG Weight Sensor: https://tinyurl.com/cjdansnu
To Be Ordered
Will need to create a platform for it. 3D Printer?

**Comment by rgarofano** [comment]
Weight Sensor Ordered
Total Cost $13.75
ETA Wed October 19th

**Comment by rgarofano** [comment]
Weight Sensor Arrived. Seems that some soldering is required.
